# Generated by Django 5.0.2 on 2024-02-22 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_postmodel_options_alter_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
